"""The PS-1 probe analyses (``scripts/ps1_probe_analysis.py``) on SYNTHETIC inputs.

P1 on the stand-in engine (``tests/fixtures/ps1_probe_engine.py``), one game per stop behaviour: in place, refused,
ignored, entered first, transitions at and beyond the window's edges, no re-listing, a refused re-order, transitioning
units that do not count, a partly accepted group, a newly full back-off destination; the premise, the cross-checks
that refuse, the secondary outcomes. P2 on trajectories generated by the frozen model and its rivals
(``tests/fixtures/ps1_trajectories.py``): every targeted claim holds on M1c data and fails on its rival's, F1 and F2
pass on consistent data and fail on planted errors, the keep flag is set aside, removals, mixed speeds and game
lengths. The registered gate rules on every verdict combination they distinguish.
"""

from __future__ import annotations

import copy
import pickle
import unittest

from miaosuan_agent.boundary import MoveCosts, Origin
from miaosuan_agent.evaluation import ps1_model as pm

from tests.fixtures import ps1_probe_engine as pe
from tests.fixtures import ps1_trajectories as tr
from miaosuan_agent.experiments.deployment_split import CANDIDATE_ID as SPLIT_ID

an = tr.analysis
COSTS = MoveCosts.from_raw(pe.cost_data(), Origin.ENGINE)
TRIGGER_K = 23
S, R, I = "SUPPORTED", "REFUTED", "INCONCLUSIVE"
_BASE = []


def base():
    if not _BASE:
        _BASE.append(pe.play_probe(SPLIT_ID)[0])
    return _BASE[0]


def p1(manifest=None, plant=None, **options):
    record, compact, windows = pe.play_probe(**options)
    if plant:
        plant(record, compact, windows)
    return an.analyze_p1(an.Game(record, compact, windows), manifest or pe.manifest(), base(), COSTS)


class P1VerdictTableTest(unittest.TestCase):
    CASES = [
        ({}, {"accepted in place": 4}, (S, S, S, S)),
        ({"stop": "refused"}, {"refused": 4}, (R, I, I, I)),
        ({"stop": "ignored"}, {"no attributable change": 4}, (R, R, I, I)),
        ({"stop": "enter"}, {"accepted after entry": 4}, (S, R, I, R)),
        ({"transition": 73}, {"accepted in place": 4}, (S, S, R, S)),
        ({"transition": 74}, {"accepted in place": 4}, (S, S, S, S)),
        ({"transition": 77}, {"accepted in place": 4}, (S, S, S, S)),
        ({"transition": 78}, {"accepted in place": 4}, (S, S, R, S)),
        ({"relist": False}, {"accepted in place": 4}, (S, S, R, S)),
        ({"refuse_moves_after": 85}, {"accepted in place": 4}, (S, S, R, S)),
        ({"uncounted": True}, {"accepted in place": 4}, (S, S, S, R)),
        ({"uncounted_after": 10}, {"accepted in place": 4}, (S, S, S, R)),
        ({"per_unit": {pe.WAITERS[0]: "refused"}}, {"accepted in place": 3, "refused": 1}, (R, S, S, S)),
        ({"per_unit": {pe.WAITERS[1]: "ignored"}}, {"accepted in place": 3, "no attributable change": 1}, (R, R, S, S)),
        ({"fill": (95, 105, 4)}, {"accepted in place": 4}, (S, S, S, S)),
    ]

    def test_each_stop_behaviour_gives_its_registered_verdicts(self) -> None:
        for options, outcomes, verdicts in self.CASES:
            with self.subTest(options=options):
                pub = p1(**options)["public"]
                self.assertTrue(pub["premise"]["reproduced"])
                self.assertEqual(pub["outcomes"], outcomes)
                self.assertEqual(tuple(pub["verdicts"][e] for e in ("E1", "E2", "E3", "E4")), verdicts)

    def test_the_default_game_in_detail(self) -> None:
        result = p1()
        pub = result["public"]
        self.assertEqual((pub["trigger_k"], pub["trigger_cur_step"], pub["stops"]), (TRIGGER_K, 22, 4))
        self.assertEqual({u["L"] for u in pub["units"]}, {75})
        self.assertTrue(all(u["back_off"]["accepted"] and u["back_off"]["arrival_k"] for u in pub["units"]))
        self.assertTrue(all(u["listed_10"] and u["in_place"] for u in pub["units"]))
        self.assertEqual(pub["offline"]["pre_trigger_decisions_rechecked"], TRIGGER_K - 1)
        self.assertTrue(pub["trigger_recomputed"]["agrees_with_hook"])
        self.assertGreater(pub["E4"]["discriminating_unit_steps"], 0)
        sec = pub["secondary"]
        self.assertEqual((sec["deadlocked_at_trigger"], sec["trigger_cycle_lengths"]), (10, [2]))
        self.assertEqual(sec["trigger_cycle_absent_from_k"], TRIGGER_K + 1)  # the stopped group became holders
        self.assertEqual(len(sec["back_off_arrivals"]), 4)
        # the stand-in's units are already traversing at the first play decision, whose timing is not observed:
        # P1-S is reported as not computed and the registered E analysis is unaffected
        self.assertEqual((pub["p1_s"]["computed"], "traversing" in pub["p1_s"]["reason"]), (False, True))

    def test_a_restart_towards_a_hex_full_only_with_transitioning_units_refutes_e4(self) -> None:
        e4 = p1(uncounted_after=10)["public"]["E4"]
        self.assertGreater(e4["discriminating_unit_steps"], 0)  # first seen waiting
        self.assertGreater(e4["restarts"], 0)  # then restarting
        self.assertEqual(e4["verdict"], R)

    def test_a_newly_full_destination_leaves_the_new_move_untested(self) -> None:
        pub = p1(fill=(95, 105, 4))["public"]
        self.assertTrue(all(u["back_off"] is None and u["released"] == 1 for u in pub["units"]))


class P1PremiseTest(unittest.TestCase):
    def test_a_different_state_before_the_trigger_is_no_reproduction(self) -> None:
        tampered = copy.deepcopy(base())
        tampered["state_steps"][5] = "0" * 16
        record, compact, windows = pe.play_probe()
        pub = an.analyze_p1(an.Game(record, compact, windows), pe.manifest(), tampered, COSTS)["public"]
        self.assertFalse(pub["premise"]["reproduced"])
        self.assertEqual(set(pub["verdicts"].values()), {I})

    def test_another_trigger_step_is_no_reproduction(self) -> None:
        pub = p1(manifest=pe.manifest(predicted_k=TRIGGER_K + 1))["public"]
        self.assertFalse(pub["premise"]["reproduced"])
        self.assertEqual(set(pub["verdicts"].values()), {I})

    def test_no_stop_is_not_evaluable(self) -> None:
        pub = p1(corridor=True, play_steps=60)["public"]
        self.assertFalse(pub["evaluable"])
        self.assertEqual(set(pub["verdicts"].values()), {I})


class P1RefusalTest(unittest.TestCase):
    def refused(self, plant, words):
        with self.assertRaises(an.Refused) as raised:
            p1(plant=plant)
        self.assertIn(words, str(raised.exception))

    def test_stops_and_notes_must_agree(self) -> None:
        def plant(record, compact, windows):  # the counts by type still match the record (I3 passes)
            step = compact["steps"][TRIGGER_K]
            index = next(i for i, a in enumerate(step["submitted"]) if a["action"]["type"] == 10)
            step["submitted"][index]["action"]["obj_id"] = pe.OCCUPANTS[0]
        self.refused(plant, "differ from the hook's notes")

    def test_capture_against_record(self) -> None:
        self.refused(lambda r, c, w: r["seats"][1]["actions_by_type"].__setitem__("10", 5), "I3")

    def test_missing_snapshot(self) -> None:
        self.refused(lambda r, c, w: w["samples"].pop(40), "I2")

    def test_channels_must_agree_on_a_stopped_unit(self) -> None:
        def plant(record, compact, windows):
            sample = next(s for s in windows["samples"] if s["k"] == TRIGGER_K + 5)
            state = pickle.loads(sample["global"])
            next(u for u in state["operators"] if u["obj_id"] == pe.WAITERS[0])["cur_hex"] = 105
            sample["global"] = pickle.dumps(state)
        self.refused(plant, "channels disagree")


class FeedbackTest(unittest.TestCase):
    def test_an_action_with_an_error_code_is_not_accepted(self) -> None:
        move = {"actor": 11, "obj_id": 5, "type": 1, "move_path": [2]}
        refused = an.Action(3, 0, move, move, (21,))
        echoed = an.Action(3, 0, move, move, (None,))
        silent = an.Action(3, 0, move, move, ())
        self.assertEqual([an.accepted(a) for a in (refused, echoed, silent)], [False, True, True])

    def test_refused_moves_in_a_stand_in_game_are_counted(self) -> None:
        record, compact, windows = pe.play_probe(refuse_moves_after=85)
        game = an.Game(record, compact, windows)
        actions = an.seat_actions(game, an.fresh_feedback(game.steps))
        refused = [a for a in actions if a.submitted.get("type") == 1 and not an.accepted(a)]
        back_offs = [a for a in refused if a.submitted["obj_id"] in pe.WAITERS and a.submitted["move_path"] == [105]]
        self.assertEqual(len(back_offs), 4)  # the four back-offs, after cur_step 85 (the candidate's are refused too)
        self.assertEqual(an.check_counts(game, actions)["with_error_feedback"], len(refused))
        self.assertTrue(all(a.k > TRIGGER_K + 60 for a in refused))


class FreshFeedbackTest(unittest.TestCase):
    def test_repeats_while_the_clock_stands_still_are_dropped(self) -> None:
        a, b = {"cur_step": 0, "message": {"type": 14, "obj_id": 1}}, {"cur_step": 0, "message": {"type": 1, "obj_id": 2}}
        steps = [{"k": 0, "cur_step": 0, "feedback": [a]}, {"k": 1, "cur_step": 0, "feedback": [a, b]},
                 {"k": 2, "cur_step": 1, "feedback": [a]}, {"k": 3, "cur_step": 1, "feedback": [a, a]}]
        fresh = an.fresh_feedback(steps)
        self.assertEqual((fresh[0], fresh[1], fresh[2], fresh[3]), ([a], [b], [a], [a]))


class TargetedClaimTest(unittest.TestCase):
    def claims(self, case, rules):
        t, _ = case(rules)
        return an.targeted(t, 0, tr.line(5))["public"]

    def test_m1c_data(self) -> None:
        pub = self.claims(tr.contention_case, "M1c")
        self.assertEqual(pub["T-a"], {"discriminating": 2, "as_predicted": 2})
        self.assertEqual(pub["T-d"]["contention_events"], 1)
        self.assertEqual((pub["T-d"]["ascending_as_predicted"], pub["T-d"]["discriminating_from_first_come"]), (1, 1))
        self.assertEqual(pub["claims"]["T-e"], S)
        self.assertEqual(pub["claims"]["T-d"], "INSUFFICIENT")
        refill = self.claims(tr.refill_case, "M1c")
        self.assertEqual(refill["T-c"], {"discriminating": 1, "as_predicted": 1})
        self.assertEqual(refill["claims"]["T-c"], "INSUFFICIENT")

    def test_rival_models_are_refuted(self) -> None:
        self.assertEqual(self.claims(tr.contention_case, "M1b")["claims"]["T-a"], R)
        m1 = self.claims(tr.contention_case, "M1")["claims"]
        self.assertEqual((m1["T-a"], m1["T-b"]), (R, R))
        self.assertEqual(self.claims(tr.refill_case, "M1")["claims"]["T-b"], R)
        desc = self.claims(tr.contention_case, "descending")["claims"]
        self.assertEqual((desc["T-d"], desc["T-e"]), (R, R))
        self.assertEqual(self.claims(tr.refill_case, "descending")["claims"]["T-e"], R)

    def test_keep_flag_events_are_set_aside(self) -> None:
        t, _ = tr.contention_case("M1c")
        entry = next(k for k in t.ks[1:] if t.b[k][5].hex == 2 and t.b[k - 1][5].hex == 1)
        for channel in (t.b, t.a):
            channel[entry][5] = channel[entry][5]._replace(keep=1)
        pub = an.targeted(t, 0, tr.line(5))["public"]
        self.assertEqual(pub["T-a"]["discriminating"], 1)
        self.assertEqual(pub["entry_rule"]["entries with the keep flag set"], 1)

    def test_t_a_sets_aside_entries_whose_next_hex_lost_a_unit_in_the_step(self) -> None:
        row = lambda h, path=(), speed=0: an.Row(h, tuple(path), speed, 0, 0, tr.SPEED, 2, 0, 0, 1, frozenset())
        before = {1: row(3, (4,), 0.2), 2: row(1, (2, 3), 0.2), 3: row(5, (3,), 0.2),
                  **{u: row(3) for u in (7, 8, 9)}}
        after = {1: row(4), 2: row(2, (3,), 0.2), 3: row(3), **{u: row(3) for u in (7, 8, 9)}}
        ent = an.entry_events({0: before, 1: after}, [0, 1])
        self.assertEqual(ent["counts"]["entries with a path left"], 1)  # unit 2 entered hex 2
        self.assertEqual(ent["T-a"], [])  # hex 3 was full before and after, but unit 1 left it in the step

    def test_t_b_refutes_an_entry_straight_from_waiting(self) -> None:
        tau = 5
        waits = [(k, 0, 4, False, 0, tr.SPEED) for k in range(10, 10 + tau - 1)]  # waiting exactly tau - 1 steps
        ep = {"uid": 1, "start": 9, "target": 3, "path": (3,), "tau": tau, "steps": waits, "end": 14,
              "outcome": "entered"}
        self.assertEqual([ok for *_, ok in an.restart_events([ep])["T-b"]], [False])
        moving = dict(ep, steps=[(10, 0, 4, False, 0, tr.SPEED)] + [(k, 0.2, 3, False, 0, tr.SPEED) for k in range(11, 15)])
        self.assertEqual([ok for *_, ok in an.restart_events([moving])["T-b"]], [True])

    def test_channel_disagreement_makes_claims_inconclusive(self) -> None:
        t, _ = tr.contention_case("M1c")
        t.a[20][5] = t.a[20][5]._replace(speed=0.5)
        self.assertIn(I, an.targeted(t, 0, tr.line(5))["public"]["claims"].values())

    def test_verdict_thresholds(self) -> None:
        self.assertEqual([an.verdict([]), an.verdict([True] * 2), an.verdict([True] * 3), an.verdict([True, False, True]),
                          an.verdict([True] * 3, extra_ok=False)], ["NOT TESTED", "INSUFFICIENT", S, R, "INSUFFICIENT"])


class FidelityTest(unittest.TestCase):
    def test_f1_on_consistent_and_rival_data(self) -> None:
        t, orders = tr.contention_case("M1c")
        f1 = an.fidelity_f1(t, 0, tr.line(5), 0, orders, set())
        self.assertTrue(f1["pass"])
        self.assertEqual((f1["hex_sequences_differ"], f1["worst_step_offset"], f1["offset_histogram"]),
                         (0, 0, {"0": f1["observed_entries"]}))
        m1 = an.fidelity_f1(*(tr.contention_case("M1")[0], 0, tr.line(5), 0, orders, set()))
        self.assertFalse(m1["pass"])
        self.assertEqual(m1["worst_step_offset"], 4)

    def test_a_planted_two_step_delay_fails_f1(self) -> None:
        t, orders = tr.contention_case("M1c")
        entry = next(k for k in t.ks[1:] if t.b[k][5].hex == 3 and t.b[k - 1][5].hex == 2)
        for channel in (t.b, t.a):
            for k in (entry, entry + 1):
                channel[k][5] = channel[entry - 1][5]
        f1 = an.fidelity_f1(t, 0, tr.line(5), 0, orders, set())
        self.assertFalse(f1["pass"])
        self.assertEqual(f1["worst_step_offset"], 2)
        self.assertEqual(f1["offset_histogram"].get("-2"), 1)

    def test_a_capacity_violation_fails_f1(self) -> None:
        t, orders = tr.contention_case("M1c")
        for channel in (t.b, t.a):
            channel[30][77] = an.Row(3, (), 0, 0, 0, tr.SPEED, 2, 0, 0, 1, frozenset())
        self.assertFalse(an.fidelity_f1(t, 0, tr.line(5), 0, orders, set())["pass"])

    def test_an_observed_hex_above_capacity_fails_f1_on_its_own(self) -> None:
        units = [pm.Unit(i, 5, 36.0, 0) for i in (1, 2, 3, 4)] + [pm.Unit(9, 1, 36.0, 0)]
        orders = {0: [("move", 9, (2, 3))]}
        t, _ = tr.generate(units, tr.line(5), 80, orders)
        self.assertTrue(an.fidelity_f1(t, 0, tr.line(5), 0, orders, set())["pass"])
        for channel in (t.b, t.a):  # a fifth unit seen in hex 5 at one step only
            channel[50][77] = an.Row(5, (), 0, 0, 0, 36.0, 2, 0, 0, 1, frozenset())
        f1 = an.fidelity_f1(t, 0, tr.line(5), 0, orders, set())
        self.assertEqual((f1["hex_sequences_differ"], f1["capacity_or_adjacency_violations"]), (0, 0))
        self.assertEqual(f1["max_observed_occupancy"]["seat observation"], 5)
        self.assertFalse(f1["pass"])

    def test_the_two_validators_must_agree(self) -> None:
        from unittest import mock
        t, orders = tr.contention_case("M1c")
        with mock.patch.object(an.pm, "validate_trajectory", return_value=["planted disagreement"]):
            with self.assertRaises(an.Refused) as raised:
                an.fidelity_f1(t, 0, tr.line(5), 0, orders, set())
        self.assertIn("validators disagree", str(raised.exception))

    def test_a_removal_that_frees_a_place_is_applied(self) -> None:
        units = [pm.Unit(i, 3, 36.0, 0) for i in (1, 2, 3, 4)] + [pm.Unit(9, 1, 36.0, 0)]
        orders = {0: [("move", 9, (2, 3))]}
        t, _ = tr.generate(units, tr.line(5), 120, orders, remove={60: [2]})
        self.assertEqual(t.b[119][9].hex, 3)  # it got in once a place was freed
        f1 = an.fidelity_f1(t, 0, tr.line(5), 0, orders, set())
        self.assertTrue(f1["pass"], f1)
        self.assertEqual(an.removals(t.b, t.ks, 0), {60: [2]})

    def test_removals_mixed_speeds_and_lengths(self) -> None:
        units = [pm.Unit(1, 1, 36.0, 0), pm.Unit(2, 1, 5.0, 2), pm.Unit(3, 4, 36.0, 0)]
        orders = {0: [("move", 1, (2, 3, 4, 5)), ("move", 2, (2, 3))]}
        for steps in (40, 400):
            t, _ = tr.generate(units, tr.line(5), steps, orders)
            for channel in (t.b, t.a):  # unit 3 leaves the observation at step 30
                for k in t.ks:
                    if k >= 30:
                        channel[k].pop(3, None)
            f1 = an.fidelity_f1(t, 0, tr.line(5), 0, orders, set())
            self.assertTrue(f1["pass"], (steps, f1))
            self.assertEqual(f1["accounting"]["steps_compared"], steps)
        self.assertEqual(an.removals(t.b, t.ks, 0), {30: [3]})

    def test_a_unit_appearing_later_is_added_as_observed(self) -> None:
        units = [pm.Unit(1, 1, 36.0, 0), pm.Unit(2, 5, 36.0, 0)]
        orders = {0: [("move", 1, (2, 3))], 30: [("move", 2, (4, 3))]}
        t, _ = tr.generate(units, tr.line(5), 80, orders)
        for channel in (t.b, t.a):  # unit 2 is first observed at decision 20
            for k in range(20):
                channel[k].pop(2)
        f1 = an.fidelity_f1(t, 0, tr.line(5), 0, orders, set())
        self.assertTrue(f1["pass"], f1)
        self.assertEqual((f1["accounting"]["eligible_units"], f1["accounting"]["units_outside_population"]), (2, 0))
        self.assertEqual(an.appearances(t.b, t.ks, 0), {20: [2]})

    def test_a_replayed_stop_takes_effect_as_m3_says(self) -> None:
        units = [pm.Unit(i, 3, tr.SPEED, 0) for i in (1, 2, 3, 4)] + [pm.Unit(5, 2, tr.SPEED, 0)]
        orders = {0: [("move", 5, (3, 4))], 20: [("stop", 5, ())], 100: [("move", 5, (1,))]}
        t, log = tr.generate(units, tr.line(5), 120, orders)
        self.assertEqual(t.b[21][5].path, ())  # waiting in front of the full hex: stopped at once
        run = an.replay(t, 0, tr.line(5), 0, orders=orders)
        self.assertEqual((run.error, run.inapplicable), (None, {}))
        self.assertEqual(run.entries, an.observed_entries(t.b, t.ks, 0))
        early = {0: orders[0], 20: orders[20], 90: [("move", 5, (1,))]}  # inside the 75-step transition
        self.assertEqual(an.replay(t, 0, tr.line(5), 0, orders=early).inapplicable,
                         {"move: not applicable in the model state": 1})

    def test_f2_with_the_surrogate(self) -> None:
        units = [pm.Unit(1, 1, 36.0, 0), pm.Unit(2, 2, 36.0, 0)]
        t, log = tr.generate(units, tr.line(5), 120, surrogate=True, objectives={5: -1, 3: -1})
        moves = [(k, u, d) for kind, k, u, d in log if kind == "move"]
        occupations = [(k, u, h) for kind, k, u, h in log if kind == "occupy"]
        self.assertTrue(moves and occupations)
        f2 = an.fidelity_f2(t, 0, tr.line(5), 0, moves, occupations)
        self.assertTrue(f2["pass"], f2)
        wrong = [(k, u, 4) for k, u, _ in moves[:1]] + moves[1:]
        self.assertFalse(an.fidelity_f2(t, 0, tr.line(5), 0, wrong, occupations)["pass"])
        self.assertFalse(an.fidelity_f2(t, 0, tr.line(5), 0, moves, occupations[1:])["pass"])
        extra = moves + [(moves[0][0], moves[0][1], 4)]  # one more recorded order: same unit and step, another hex
        f2 = an.fidelity_f2(t, 0, tr.line(5), 0, extra, occupations)
        self.assertEqual((f2["orders"]["predicted_unmatched"], f2["orders"]["recorded_matched"]), (0, len(moves)))
        self.assertFalse(f2["pass"])


def p2(f1="PASS", f2="PASS", claims=None, occupancy=4, disagreements=0):
    claims = claims or {"T-a": S, "T-b": S, "T-c": "NOT TESTED", "T-d": S, "T-e": S}
    return {"F1": {"verdict": f1, "max_observed_occupancy": {"x": occupancy}}, "F2": {"verdict": f2},
            "targeted": {"claims": claims}, "channels": {"disagreeing_unit_entries": disagreements}}


def p1_out(e1=S, e2=S, e3=S, e4=S, outcomes=None):
    return {"verdicts": {"E1": e1, "E2": e2, "E3": e3, "E4": e4}, "evaluable": True,
            "outcomes": outcomes or {"accepted in place": 4}, "channels": {"disagreeing_unit_entries": 0},
            "max_occupancy": {"x": 4}, "premise": {"state_digests_equal_to_trigger": True},
            "integrity": {"replay_mismatches": 0, "gate_rejections": 0, "contract_errors": 0},
            "offline": {"pre_trigger_decisions_rechecked": 10}}


class GateTest(unittest.TestCase):
    def g(self, p1_, p2_, certificate=None):
        return an.gates(p1_, p2_, certificate)

    def test_the_gate_table(self) -> None:
        feasible = {"verdict": "feasible"}
        ready = self.g(p1_out(), p2(), feasible)
        self.assertEqual((ready["G2"], ready["G3"], ready["G5"]), ("PASS", "PASS", "READY_FOR_PROSPECTIVE_VALIDATION"))
        self.assertEqual(self.g(p1_out(), p2())["G3"], "UNRESOLVED")  # no certificate recomputed
        self.assertEqual(self.g(p1_out(e1=R, outcomes={"refused": 4}), p2())["G5"], "SHELVE")
        self.assertEqual(self.g(p1_out(e1=R, outcomes={"refused": 1, "accepted in place": 3}), p2())["G5"], "REVISE")
        self.assertEqual(self.g(p1_out(e2=R), p2(), feasible)["G5"], "REVISE")
        self.assertEqual(self.g(p1_out(e4=I), p2(), feasible)["G5"], "NEEDS_ENGINE_PROBE")
        self.assertEqual(self.g(p1_out(), p2(f1="FAIL"), feasible)["G3"], "FAIL")
        self.assertEqual(self.g(p1_out(), p2(f2="FAIL"), feasible)["G5"], "REVISE")
        self.assertEqual(self.g(p1_out(), p2(f1="INCONCLUSIVE"), feasible)["G3"], "UNRESOLVED")
        insufficient = {"T-a": S, "T-b": S, "T-c": "NOT TESTED", "T-d": "INSUFFICIENT", "T-e": S}
        self.assertEqual(self.g(p1_out(), p2(claims=insufficient), feasible)["G5"], "NEEDS_ENGINE_PROBE")
        refuted = dict(insufficient, **{"T-d": R})
        self.assertEqual(self.g(p1_out(), p2(claims=refuted), feasible)["G3"], "FAIL")
        rewait = dict(insufficient, **{"T-d": S, "T-c": "INSUFFICIENT"})
        self.assertEqual(self.g(p1_out(), p2(claims=rewait), feasible)["G3"], "PASS")

    def test_g1_records_a_contradiction(self) -> None:
        self.assertIn("contradiction", self.g(p1_out(), p2(disagreements=1))["G1"])
        self.assertIn("contradiction", self.g(p1_out(), p2(occupancy=5))["G1"])


if __name__ == "__main__":
    unittest.main()
