"""Play the games of one Sprint 12 stage card, one game at a time (``docs/SPRINT12_V3_SCREEN.md``).

    python scripts/run_s12_stage.py --python PYTHON --sdk-archive ZIP --stage P1|P2|A1|A2
        [--engine-install DIR] [--work DIR]

Before the first game: not root; a clean, committed tree; the stage card committed and byte-identical to a fresh
build from the committed reports; the card's pins (frozen files, rules, policy identities, budget) equal to this
checkout; for P2, A1 and A2 the previous stage's committed report regenerated byte for byte from the private records
(so the decision that permits this stage is the frozen rules' decision on the real games); the inputs staged and
checked. Then, for each game in card order: the ledger-counted ceiling (12 sessions after 2786) is checked, the game
is played by ``scripts/run_s12_game.py`` in the registered evaluator's isolation (an empty environment, the persistent
installation's ``home/`` as HOME, its ``site/`` and this checkout's ``src`` on PYTHONPATH, PYTHONHASHSEED=0, no GPU,
the runtime's thread variables, a hard timeout), and before the next game starts the game's facts are computed and
every immediate stop (S1 to S14, the ledger audit included) is checked. Any non-zero game status or any stop ends the
stage at once. A game that was started earlier and left no record stops the stage; no game is retried.

Exit status: 0 every game of the card completed without a stop; 3 a stop fired; 1 a game did not complete; 2 refused
before any game.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any, Callable, Dict, List

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "src"))

from miaosuan_agent.evaluation import execution as ex  # noqa: E402
from miaosuan_agent.evaluation import exploratory as xp  # noqa: E402
from miaosuan_agent.evaluation import s12_screen as sc  # noqa: E402

TIMEOUT_SECONDS = 2100


def load(name: str) -> Any:
    spec = importlib.util.spec_from_file_location(name, REPO_ROOT / "scripts" / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def refuse(message: str) -> int:
    print(f"REFUSED: {message}", file=sys.stderr)
    return 2


def git_dirty(repo: Path) -> bool:
    status = subprocess.run(["git", "-C", str(repo), "status", "--porcelain", "--untracked-files=no"],
                            capture_output=True, text=True, check=True)
    return bool(status.stdout.strip())


def isolated_env(install: Path, repo: Path, runtime: str) -> Dict[str, str]:
    """The registered evaluator's game environment (``scripts/run_evaluation.sh``), built explicitly."""
    env = {"HOME": str(install / "home"), "PATH": "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin", "LANG": "C.UTF-8",
           "PYTHONNOUSERSITE": "1", "PYTHONDONTWRITEBYTECODE": "1", "PYTHONHASHSEED": "0", "CUDA_VISIBLE_DEVICES": "",
           "PYTHONPATH": f"{install / 'site'}:{repo / 'src'}"}
    env.update(ex.runtime_env(runtime))
    return env


def launch_subprocess(args: argparse.Namespace, card: Dict[str, Any], game_id: str, commit: str) -> int:
    cwd = args.work / "cwd" / "a" / "b"
    cwd.mkdir(parents=True, exist_ok=True)
    log = args.work / "logs" / f"{game_id}.log"
    command = ["timeout", "--signal=TERM", "--kill-after=30", str(TIMEOUT_SECONDS), args.python,
               str(REPO_ROOT / "scripts" / "run_s12_game.py"), "--card", card["card_id"], "--work", str(args.work),
               "game", "--game-id", game_id, "--engine-install", str(args.engine_install), "--harness-commit", commit]
    with log.open("w", encoding="utf-8") as handle:
        status = subprocess.run(command, cwd=cwd, env=isolated_env(args.engine_install, REPO_ROOT,
                                                                    ex.registered(card)["runtime"]),
                                stdout=handle, stderr=subprocess.STDOUT).returncode
    print(log.read_text(encoding="utf-8").strip().splitlines()[-1:] or ["(no output)"])
    return status


def run_stage(args: argparse.Namespace, launch: Callable[..., int] = launch_subprocess,
              check_previous: bool = True, stage_inputs: bool = True) -> int:
    """The stage runner. ``launch`` plays one game and returns its exit status (tests pass an in-process stand-in)."""
    cards = load("build_s12_card")
    analysis = load("s12_screen_analysis")
    card_id = sc.CARD_IDS[args.stage]
    manifest = REPO_ROOT / "evaluation" / card_id / "manifest.json"
    if hasattr(os, "getuid") and os.getuid() == 0:
        return refuse("the engine never runs as root")
    if git_dirty(REPO_ROOT):
        return refuse("screen games run only from a clean, committed tree")
    if not manifest.exists():
        return refuse(f"no committed stage card {card_id}")
    try:
        fresh = cards.build_stage(args.stage)
    except sc.NotPermitted as exc:
        return refuse(f"the committed reports do not permit {card_id}: {exc}")
    if sc.dump(fresh) != manifest.read_text(encoding="utf-8"):
        return refuse(f"{card_id} does not rebuild byte-identically")
    card = json.loads(manifest.read_text(encoding="utf-8"))
    problems = sc.card_problems(card, REPO_ROOT)
    if problems:
        return refuse("; ".join(problems))
    if check_previous and args.stage != "P1":
        previous = sc.STAGE_ORDER[sc.STAGE_ORDER.index(args.stage) - 1]
        report, _ = analysis.stage_report(previous)
        if sc.dump(report) != (REPO_ROOT / sc.report_path(previous)).read_text(encoding="utf-8"):
            return refuse(f"the committed report of {previous} does not regenerate from the private records")
    args.work.mkdir(parents=True, exist_ok=True)
    for sub in ("games", "started", "logs", "capture"):
        (args.work / sub).mkdir(exist_ok=True)
    if stage_inputs:
        subprocess.run([args.python, str(REPO_ROOT / "scripts" / "run_evaluation.py"), "--evaluation", card_id,
                        "--manifest", str(manifest), "--work", str(args.work), "stage", "--sdk-archive",
                        str(args.sdk_archive)], check=True, capture_output=True)
    archive_before = sha256(args.sdk_archive) if stage_inputs else None
    commit = subprocess.run(["git", "-C", str(REPO_ROOT), "rev-parse", "HEAD"], capture_output=True, text=True,
                            check=True).stdout.strip()
    ledger = args.engine_install / "usage-ledger.jsonl"
    for entry in card["games"]:
        game_id = entry["game_id"]
        if (args.work / "games" / f"{game_id}.json").exists():
            print(f"recorded already: {game_id}")
            continue
        if (args.work / "started" / game_id).exists():
            print(f"STOP: {game_id} was started earlier and left no record", file=sys.stderr)
            return 3
        problem = xp.budget_problem(card, ledger, 1)
        if problem:
            print(f"STOP: {problem}", file=sys.stderr)
            return 3
        (args.work / "started" / game_id).write_text(commit + "\n", encoding="utf-8")
        status = launch(args, card, game_id, commit)
        facts = analysis.game_facts(card, entry, REPO_ROOT, args.work)
        stops: Dict[str, List[str]] = dict((facts or {}).get("stops") or {}) if facts else {"S4": ["no record"]}
        for code, problems in analysis.ledger_problems(REPO_ROOT, args.engine_install).items():
            stops.setdefault(code, []).extend(problems)
        codes = [c for c in sc.STOP_CODES if stops.get(c)]
        print(f"{game_id}: exit {status}, stops {codes or 'none'}")
        if codes:
            for code in codes:
                for problem in stops[code][:5]:
                    print(f"  {code}: {problem}", file=sys.stderr)
            print("STOP: an immediate stop fired; the screen stops and returns to the owner", file=sys.stderr)
            return 3
        if status != 0:
            print(f"STOP: {game_id} exited with status {status}", file=sys.stderr)
            return 1 if status == 1 else 3
    if stage_inputs and sha256(args.sdk_archive) != archive_before:
        print("STOP: the SDK archive changed during the stage", file=sys.stderr)
        return 3
    problems = sc.card_problems(card, REPO_ROOT)
    if problems:
        print(f"STOP: after the stage: {'; '.join(problems)}", file=sys.stderr)
        return 3
    print(f"stage {args.stage} finished; write its report with scripts/s12_screen_analysis.py report --stage "
          f"{args.stage}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--python", required=True)
    parser.add_argument("--sdk-archive", type=Path, required=True)
    parser.add_argument("--stage", required=True, choices=sc.STAGE_ORDER)
    parser.add_argument("--engine-install", type=Path, default=REPO_ROOT / "local" / "engines" / "sdk-4.1.0")
    parser.add_argument("--work", type=Path)
    args = parser.parse_args()
    args.engine_install = args.engine_install.resolve()
    args.sdk_archive = args.sdk_archive.resolve()
    args.work = (args.work or REPO_ROOT / "local" / "evaluation" / sc.CARD_IDS[args.stage]).resolve()
    if not (args.engine_install / "install-manifest.json").exists():
        return refuse(f"no persistent engine installation at {args.engine_install}")
    return run_stage(args)


if __name__ == "__main__":
    sys.exit(main())
