"""Run one registered phase of the T9 confirmatory study (``docs/T9_CONFIRMATION.md``).

    PYTHON scripts/run_t9_confirmation.py --python PYTHON --sdk-archive ZIP --phase A|D|B|C
                                          [--engine-install DIR] [--work DIR]

Pre-run checks, each of which refuses the phase: not root; a clean, committed tree; the manifest rebuilds
byte-identically; every pinned implementation and test file and every policy source equals its registered digest;
the qualified scheduler's identity equals the registered one; for phases after A, the committed gate file of the
previous phase says CONTINUE, permits this phase and is regenerated byte-identically from the records; the ledger
shows no unclosed session, every session after the study's base session belongs to a game of an earlier phase of
this study (and each such game is recorded), and the phase's games fit under the study's cap.

The phase's games are then handed, in registered order, to the qualified scheduler (``scripts/run_game_pool.py``,
unchanged) with the registered worker count and runtime; each game is ``scripts/run_t9_confirmation_game.py``.
Dispatch stops after 3 consecutive games that did not complete, on any other exit status and on a signal; nothing
is retried or replaced. After the run the policy sources, the pinned files, the SDK archive and the ledger are
checked again. The phase's analysis and gate are ``scripts/t9_confirmation_analysis.py phase --phase X``.

Exit status: the pool's (0 every started game exited 0 or 1), 2 a refused pre-run check, 5 a failed post-run check.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path
from types import SimpleNamespace
from typing import Any, List

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "src"))

from miaosuan_agent import engine_install as ei  # noqa: E402
from miaosuan_agent.evaluation import manifest as mf  # noqa: E402
from miaosuan_agent.evaluation import t9_confirmation as tc  # noqa: E402

GAME_SCRIPT = REPO_ROOT / "scripts" / "run_t9_confirmation_game.py"
MANIFEST = REPO_ROOT / "evaluation" / tc.STUDY_ID / "manifest.json"


def load_script(name: str) -> Any:
    spec = importlib.util.spec_from_file_location(name.replace("/", "_"), REPO_ROOT / "scripts" / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def git(*args: str) -> str:
    return subprocess.run(["git", "-C", str(REPO_ROOT), *args], capture_output=True, text=True, check=True).stdout


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def identity_problems(manifest: Any) -> List[str]:
    problems = []
    rev = load_script("run_evaluation")
    for policy, entry in sorted(manifest["policies"].items()):
        if rev.registered_source_digest(entry["policy_source"]) != entry["policy_source"]["sha256"]:
            problems.append(f"policy source of {policy}")
    for rel, digest in sorted({**manifest["files"], **manifest["tests"]}.items()):
        if not (REPO_ROOT / rel).exists() or tc.normalized_sha256(REPO_ROOT / rel) != digest:
            problems.append(f"pinned file {rel}")
    if load_script("run_game_pool").scheduler_identity() != manifest["execution"]["scheduler"]:
        problems.append("scheduler identity")
    return problems


def refuse(message: str) -> int:
    print(f"REFUSED: {message}", file=sys.stderr)
    return 2


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--python", required=True)
    parser.add_argument("--sdk-archive", type=Path, required=True)
    parser.add_argument("--phase", required=True, choices=tc.PHASE_ORDER)
    parser.add_argument("--engine-install", type=Path, default=REPO_ROOT / "local" / "engines" / "sdk-4.1.0")
    parser.add_argument("--work", type=Path, default=REPO_ROOT / "local" / "evaluation" / tc.STUDY_ID)
    args = parser.parse_args()
    if hasattr(os, "geteuid") and os.geteuid() == 0:
        return refuse("the engine never runs as root")
    if git("status", "--porcelain").strip():
        return refuse("a registered phase runs only from a clean, committed tree")
    build = load_script("build_t9_confirmation_manifest")
    if not build.matches():
        return refuse("the manifest does not rebuild byte-identically")
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    digest = mf.digest(manifest)
    problems = identity_problems(manifest)
    if problems:
        return refuse(f"identities differ from the registration: {problems}")
    phase = args.phase
    index = tc.PHASE_ORDER.index(phase)
    analysis = load_script("t9_confirmation_analysis")
    install = ei.EngineInstall(args.engine_install.resolve())
    work = args.work.resolve()
    if index > 0:
        previous = tc.PHASE_ORDER[index - 1]
        committed = REPO_ROOT / "evaluation" / tc.STUDY_ID / f"phase-{previous}.json"
        if not committed.exists():
            return refuse(f"no committed gate of phase {previous}")
        gate = json.loads(committed.read_text(encoding="utf-8"))["gate"]
        if gate["decision"] != "CONTINUE" or gate["permits"] != phase:
            return refuse(f"the gate of phase {previous} does not permit phase {phase}: {gate}")
        fresh = analysis.phase_text(manifest, previous, work, ei.read_ledger(install))
        if fresh != committed.read_text(encoding="utf-8"):
            return refuse(f"the committed gate of phase {previous} does not regenerate from the records")
    try:
        with ei.exclusive_window(install):
            ledger = ei.read_ledger(install)
    except ei.InstallRefused as exc:
        return refuse(str(exc))
    if ei.unclosed_sessions(ledger):
        return refuse(f"unclosed sessions {ei.unclosed_sessions(ledger)}")
    audit = tc.ledger_audit(ledger, digest, [g["game_id"] for g in manifest["games"]])
    if not audit["ok"]:
        return refuse(f"ledger audit: {audit['problems']}")
    earlier = {g["game_id"] for g in manifest["games"] if tc.PHASE_ORDER.index(g["phase"]) < index}
    if set(audit["games"]) != earlier:
        return refuse("the study's sessions in the ledger are not exactly the games of the earlier phases")
    missing = sorted(g for g in earlier if not (work / "games" / f"{g}.json").exists())
    if missing:
        return refuse(f"earlier games without a record: {missing[:5]}")
    queue = [g["game_id"] for g in manifest["games"] if g["phase"] == phase]
    if audit["sessions"] + len(queue) > manifest["budget"]["session_cap"]:
        return refuse(f"{audit['sessions']} sessions used; {len(queue)} more exceed the cap "
                      f"{manifest['budget']['session_cap']}")
    print(f"phase {phase}: {len(queue)} games; study sessions used {audit['sessions']}, cap "
          f"{manifest['budget']['session_cap']}; manifest {digest}", flush=True)

    archive = args.sdk_archive.resolve()
    archive_before = sha256(archive)
    (work / "logs").mkdir(parents=True, exist_ok=True)
    with open(work / "logs" / f"stage-{phase}.log", "w", encoding="utf-8") as log:
        subprocess.run([args.python, str(REPO_ROOT / "scripts" / "run_evaluation.py"), "--evaluation", tc.STUDY_ID,
                        "--manifest", str(MANIFEST), "--work", str(work), "stage", "--sdk-archive", str(archive)],
                       check=True, stdout=log, env={**os.environ, "PYTHONNOUSERSITE": "1"})
    verify_before = ei.verify(install)
    if not (verify_before["integrity"]["ok"] and verify_before["state_continuous"]):
        return refuse("the installation does not verify")
    (work / "pool").mkdir(parents=True, exist_ok=True)
    queue_file = work / "pool" / f"queue-{phase}.txt"
    with open(queue_file, "x", encoding="utf-8") as handle:
        handle.write("\n".join(queue) + "\n")
    pool = load_script("run_game_pool")
    pool_args = SimpleNamespace(evaluation=tc.STUDY_ID, work=str(work), engine_install=str(install.root),
                                python=args.python, workers=manifest["execution"]["workers"],
                                games_file=str(queue_file), harness_commit=git("rev-parse", "HEAD").strip(),
                                harness_dirty=False, purpose="evaluation", timeout=2100.0,
                                stop_after_failures=manifest["execution"]["stop_after_consecutive_failures"],
                                runtime=manifest["execution"]["runtime"],
                                expected_scheduler=manifest["execution"]["scheduler"])
    status = pool.run(pool_args, game_script=GAME_SCRIPT)

    after = []
    if identity_problems(manifest):
        after.append("identities changed during the run")
    if sha256(archive) != archive_before:
        after.append("the SDK archive changed during the run")
    verify_after = ei.verify(install)
    if not (verify_after["integrity"]["ok"] and verify_after["state_continuous"]) or verify_after["unclosed_session"]:
        after.append("the installation does not verify after the run")
    audit = tc.ledger_audit(ei.read_ledger(install), digest, [g["game_id"] for g in manifest["games"]])
    if not audit["ok"]:
        after.append(f"ledger audit after the run: {audit['problems']}")
    with open(work / "logs" / f"verify-{phase}.json", "w", encoding="utf-8") as handle:
        json.dump({"before": verify_before, "after": verify_after, "ledger_audit": audit, "pool_status": status},
                  handle, indent=1, sort_keys=True)
    print(f"phase {phase} finished: pool status {status}; study sessions {audit['sessions']}; installation "
          f"integrity {verify_after['integrity']['ok']}, state continuous {verify_after['state_continuous']}", flush=True)
    if after:
        print("POST-RUN CHECK FAILED: " + "; ".join(after), file=sys.stderr)
        return 5
    return status


if __name__ == "__main__":
    sys.exit(main())
